[option]
exclude_paths = []
indent = 4 
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"

[rules]
blocking_assignment_in_always_ff = true
case_default = true
default_nettype_none = false
enum_with_type = true
explicit_case_default = true
explicit_if_else = true
for_with_begin = true
function_same_as_system_function = true
function_with_automatic = true
generate_case_with_label = true
generate_for_with_label = true
generate_if_with_label = true
generate_keyword_forbidden = true
generate_keyword_required = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = true
if_with_begin = true
inout_with_tri = true
input_with_var = false
interface_port_with_modport = true
legacy_always = true
level_sensitive_always = true
localparam_explicit_type = true
localparam_type_twostate = true
loop_variable_declaration = true
lowercamelcase_interface = true
lowercamelcase_module = false
lowercamelcase_package = true
non_ansi_module = true
non_blocking_assignment_in_always_comb = true
output_with_var = false
parameter_explicit_type = true
parameter_in_package = true
parameter_type_twostate = true
prefix_inout = false
prefix_input = false
prefix_instance = true
prefix_interface = true
prefix_module = false
prefix_output = false
prefix_package = false
priority_keyword = true
sequential_block_in_always_comb = true
sequential_block_in_always_ff = true
sequential_block_in_always_latch = true
style_commaleading = false
style_indent = true
style_keyword_0or1space = true
style_keyword_0space = true
style_keyword_1or2space = true
style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = true
style_keyword_end = true
style_keyword_maybelabel = true
style_keyword_newline = true
tab_character = true
unique0_keyword = true
unique_keyword = true
uppercamelcase_interface = true
uppercamelcase_module = false
uppercamelcase_package = true
wire_reg = false

